//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards.Repository.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<RegionCoordinador> RegionCoordinador { get; set; }
        public virtual DbSet<RegionUbicacion> RegionUbicacion { get; set; }
        public virtual DbSet<Tc_Incidentes> Tc_Incidentes { get; set; }
        public virtual DbSet<V_GeneralNivelDistrito> V_GeneralNivelDistrito { get; set; }
        public virtual DbSet<V_GeneralNivelGlobal> V_GeneralNivelGlobal { get; set; }
        public virtual DbSet<V_GeneralNivelRegion> V_GeneralNivelRegion { get; set; }
    }
}
