//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elecciones
    {
        public int Id { get; set; }
        public int IdTipoEleccion { get; set; }
        public int Pan { get; set; }
        public int Pt { get; set; }
        public int Pri { get; set; }
        public int Pvem { get; set; }
        public int Pna { get; set; }
        public int Prd { get; set; }
        public int Morena { get; set; }
        public int Otros { get; set; }
    }
}
