//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCoordinador
    {
        public int IdRegionCoordinador { get; set; }
        public int IdRegion { get; set; }
        public string Coordinador { get; set; }
        public string Telefonos { get; set; }
    }
}
