//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tc_Incidentes
    {
        public int Inc_Id { get; set; }
        public string Inc_Num { get; set; }
        public string Inc_Concepto { get; set; }
        public Nullable<int> Inc_Ref { get; set; }
    }
}
