//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GeneralNivelDistrito
    {
        public double D_DttoElec { get; set; }
        public string D_TipoEleccion { get; set; }
        public int IdRegion { get; set; }
        public Nullable<int> AsistenciaConteo { get; set; }
        public Nullable<int> AsistenciaCasillas { get; set; }
        public Nullable<int> InstalacionConteo { get; set; }
        public Nullable<int> InstalacionCasillas { get; set; }
        public Nullable<int> IncidentesConteo { get; set; }
        public Nullable<int> IncidentesCasillas { get; set; }
        public Nullable<int> DesayunoConteo { get; set; }
        public Nullable<int> DesayunoCasillas { get; set; }
        public Nullable<int> ComidaConteo { get; set; }
        public Nullable<int> ComidaCasillas { get; set; }
        public Nullable<int> TotalCasillas { get; set; }
    }
}
