//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GeneralNivelRegion
    {
        public double D_DttoElec { get; set; }
        public int IdRegion { get; set; }
        public double S_IdSeccion { get; set; }
        public string TC_Descripcion { get; set; }
        public int AsistenciaEstatus { get; set; }
        public string NotaAsistencia { get; set; }
        public int InstalacionEstatus { get; set; }
        public string NotaInstalacion { get; set; }
        public int IncidentesEstatus { get; set; }
        public string NotaIncidente { get; set; }
        public int DesayunoEstatus { get; set; }
        public string NotaDesayuno { get; set; }
        public int ComidaEstatus { get; set; }
        public string NotaComida { get; set; }
        public int CodigoIncidente { get; set; }
    }
}
